qt_select_res2_1 """select count(*) from t1 join t2 on c1 = c2;"""
qt_select_res2_2 """select count(*) from t1 join [shuffle] t2 on c1 = c2;"""
qt_select_res2_3 """select count(*) from t1 join [broadcast] t2 on c1 = c2;"""

qt_select_res3_1 """select count(*) from t1 join t2 on c1 = c2 join [shuffle] t3 on c2 = c3;"""
qt_select_res3_2 """select count(*) from t1 join [shuffle] t2 on c1 = c2 join t3 on c2 = c3;"""
qt_select_res3_3 """select count(*) from t1 join t2 on c1 = c2 join [broadcast] t3 on c2 = c3;"""
qt_select_res3_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 join t3 on c2 = c3;"""
qt_select_res3_5 """select count(*) from t1 join [broadcast] t2 on c1 = c2 join [shuffle] t3 on c2 = c3;"""
qt_select_res3_6 """select count(*) from t1 join [shuffle] t2 on c1 = c2 join [broadcast] t3 on c2 = c3;"""
qt_select_res3_7 """select count(*) from t1 join [shuffle] t2 on c1 = c2 join [shuffle] t3 on c2 = c3;"""
qt_select_res3_8 """select count(*) from t1 join [broadcast] t2 on c1 = c2 join [broadcast] t3 on c2 = c3;"""

qt_select_res4_1 """select count(*) from t1 join [shuffle] t2 on c1 = c2 join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res4_2 """select count(*) from t1 join [broadcast] t2 on c1 = c2 join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res4_3 """select count(*) from t1 join t2 on c1 = c2 join [broadcast] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res4_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res4_5 """select count(*) from t1 join [broadcast] t2 on c1 = c2 join [shuffle] t3 on c2 = c3 join t4 on c3 = c4;"""

qt_select_res5_1 """select count(*) from t1 join [shuffle] t2 on c1 > c2;"""
qt_select_res5_2 """select count(*) from t1 join [broadcast] t2 on c1 > c2;"""

qt_select_res6_1 """select count(*) from t1 join [shuffle] t2 on c1 > c2 join t3 on c2 > c3 where c1 < 100;"""
qt_select_res6_2 """select count(*) from t1 join t2 on c1 > c2 join t3 on c2 > c3 where c1 < 100;"""

// (A leftjoin B on (Pab)) leftjoin C on (Pac) = (A leftjoin C on (Pac)) leftjoin B on (Pab)
qt_select_res7_1 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join t3 on c1 = c3;"""
qt_select_res7_2 """select count(*) from t1 left join t2 on c1 = c2 left join [shuffle] t3 on c1 = c3;"""

qt_select_res8_1 """select count(*) from t1 left join t2 on c1 = c2 left join [broadcast] t3 on c1 = c3 where c1 between 100 and 300;"""
qt_select_res8_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c1 = c3 where c1 between 100 and 300;"""

qt_select_res9_1 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join [broadcast] t3 on c1 = c3 where c3 between 100 and 300;"""
qt_select_res9_2 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [shuffle] t3 on c1 = c3 where c3 between 100 and 300;"""

qt_select_res10_1 """select count(*) from t1 left join t2 on c1 = c2 left join t3 on c1 = c3 where c2 between 100 and 300;"""
qt_select_res10_2 """select count(*) from t1 left join t2 on c1 = c2 left join t3 on c1 = c3 where c2 between 100 and 300;"""

qt_select_res11_1 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [broadcast] t3 on c1 > c3 where c3 between 100 and 300;"""
qt_select_res11_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c1 > c3 where c3 between 100 and 300;"""

// (A leftjoin B on (Pab)) leftjoin C on (Pbc) = A leftjoin (B leftjoin C on (Pbc)) on (Pab)
qt_select_res12_1 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res12_2 """select count(*) from t1 left join t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""

qt_select_res13_1 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3 where c1 between 100 and 300;"""
qt_select_res13_2 """select count(*) from t1 left join t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 where c1 between 100 and 300;"""

qt_select_res14_1 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 where c2 between 100 and 300;"""
qt_select_res14_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3 where c2 between 100 and 300;"""

qt_select_res15_1 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3 where c3 between 100 and 300;"""
qt_select_res15_2 """select count(*) from t1 left join t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 where c3 between 100 and 300;"""

//// test outer join which can not swap
// A leftjoin (B join C on (Pbc)) on (Pab) != (A leftjoin B on (Pab)) join C on (Pbc) output should be unused when explain
// this can be done because left join can be eliminated to inner join
qt_select_res16_1 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 join t3 on c2 = c3;"""
qt_select_res16_2 """select count(*) from t1 left join t2 on c1 = c2 join [broadcast] t3 on c2 = c3;"""

// inner join + full outer join
qt_select_res17_1 """select count(*) from t1 join t2 on c1 = c2 full join t3 on c2 = c3;"""
qt_select_res17_2 """select count(*) from t1 join [broadcast] t2 on c1 = c2 full join t3 on c2 = c3;"""
qt_select_res17_3 """select count(*) from t1 join t2 on c1 = c2 full join [broadcast] t3 on c2 = c3;"""
qt_select_res17_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 full join [broadcast] t3 on c2 = c3;"""
qt_select_res17_5 """select count(*) from t1 join [shuffle] t2 on c1 = c2 full join t3 on c2 = c3;"""
qt_select_res17_6 """select count(*) from t1 join t2 on c1 = c2 full join [shuffle] t3 on c2 = c3;"""
qt_select_res17_7 """select count(*) from t1 join [shuffle] t2 on c1 = c2 full join [shuffle] t3 on c2 = c3;"""
qt_select_res17_8 """select count(*) from t1 join [shuffle] t2 on c1 = c2 full join [broadcast] t3 on c2 = c3;"""
qt_select_res17_9 """select count(*) from t1 join [broadcast] t2 on c1 = c2 full join [shuffle] t3 on c2 = c3;"""

// inner join + left outer join
qt_select_res18_1 """select count(*) from t1 join t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res18_2 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res18_3 """select count(*) from t1 join t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""
qt_select_res18_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""
qt_select_res18_5 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res18_6 """select count(*) from t1 join t2 on c1 = c2 left join [shuffle] t3 on c2 = c3;"""
qt_select_res18_7 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left join [shuffle] t3 on c2 = c3;"""
qt_select_res18_8 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""
qt_select_res18_9 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left join [shuffle] t3 on c2 = c3;"""

// inner join + right outer join
qt_select_res19_1 """select count(*) from t1 join t2 on c1 = c2 right join t3 on c2 = c3;"""
qt_select_res19_2 """select count(*) from t1 join [broadcast] t2 on c1 = c2 right join t3 on c2 = c3;"""
qt_select_res19_3 """select count(*) from t1 join t2 on c1 = c2 right join [broadcast] t3 on c2 = c3;"""
qt_select_res19_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3;"""
qt_select_res19_5 """select count(*) from t1 join [shuffle] t2 on c1 = c2 right join t3 on c2 = c3;"""
qt_select_res19_6 """select count(*) from t1 join t2 on c1 = c2 right join [shuffle] t3 on c2 = c3;"""
qt_select_res19_7 """select count(*) from t1 join [shuffle] t2 on c1 = c2 right join [shuffle] t3 on c2 = c3;"""
qt_select_res19_8 """select count(*) from t1 join [shuffle] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3;"""
qt_select_res19_9 """select count(*) from t1 join [broadcast] t2 on c1 = c2 right join [shuffle] t3 on c2 = c3;"""

// inner join + semi join
qt_select_res20_1 """select count(*) from t1 join t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res20_2 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res20_3 """select count(*) from t1 join t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res20_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res20_5 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res20_6 """select count(*) from t1 join t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""
qt_select_res20_7 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""
qt_select_res20_8 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res20_9 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""

// inner join + anti join
qt_select_res21_1 """select count(*) from t1 join t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res21_2 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res21_3 """select count(*) from t1 join t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res21_4 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res21_5 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res21_6 """select count(*) from t1 join t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""
qt_select_res21_7 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""
qt_select_res21_8 """select count(*) from t1 join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res21_9 """select count(*) from t1 join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""

// left join + left join
qt_select_res22_1 """select count(*) from t1 left join t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res22_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res22_3 """select count(*) from t1 left join t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""
qt_select_res22_4 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""
qt_select_res22_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join t3 on c2 = c3;"""
qt_select_res22_6 """select count(*) from t1 left join t2 on c1 = c2 left join [shuffle] t3 on c2 = c3;"""
qt_select_res22_7 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [shuffle] t3 on c2 = c3;"""
qt_select_res22_8 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3;"""
qt_select_res22_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join [shuffle] t3 on c2 = c3;"""

// left join + right join
qt_select_res23_1 """select count(*) from t1 left join t2 on c1 = c2 right join t3 on c2 = c3;"""
qt_select_res23_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 right join t3 on c2 = c3;"""
qt_select_res23_3 """select count(*) from t1 left join t2 on c1 = c2 right join [broadcast] t3 on c2 = c3;"""
qt_select_res23_4 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3;"""
qt_select_res23_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join t3 on c2 = c3;"""
qt_select_res23_6 """select count(*) from t1 left join t2 on c1 = c2 right join [shuffle] t3 on c2 = c3;"""
qt_select_res23_7 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join [shuffle] t3 on c2 = c3;"""
qt_select_res23_8 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3;"""
qt_select_res23_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 right join [shuffle] t3 on c2 = c3;"""

// left join + semi join
qt_select_res24_1 """select count(*) from t1 left join t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res24_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res24_3 """select count(*) from t1 left join t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res24_4 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res24_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res24_6 """select count(*) from t1 left join t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""
qt_select_res24_7 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""
qt_select_res24_8 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res24_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""

// left join + anti join
qt_select_res25_1 """select count(*) from t1 left join t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res25_2 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res25_3 """select count(*) from t1 left join t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res25_4 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res25_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res25_6 """select count(*) from t1 left join t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""
qt_select_res25_7 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""
qt_select_res25_8 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res25_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""

// right join + semi join
qt_select_res26_1 """select count(*) from t1 right join t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res26_2 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res26_3 """select count(*) from t1 right join t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res26_4 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res26_5 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3;"""
qt_select_res26_6 """select count(*) from t1 right join t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""
qt_select_res26_7 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""
qt_select_res26_8 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3;"""
qt_select_res26_9 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3;"""

// right join + anti join
qt_select_res27_1 """select count(*) from t1 right join t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res27_2 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res27_3 """select count(*) from t1 right join t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res27_4 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res27_5 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3;"""
qt_select_res27_6 """select count(*) from t1 right join t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""
qt_select_res27_7 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""
qt_select_res27_8 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3;"""
qt_select_res27_9 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3;"""

// semi join + anti join
qt_select_res28_1 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join t3 on c1 = c3;"""
qt_select_res28_2 """select count(*) from t1 left semi join [broadcast] t2 on c1 = c2 left anti join t3 on c1 = c3;"""
qt_select_res28_3 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3;"""
qt_select_res28_4 """select count(*) from t1 left semi join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3;"""
qt_select_res28_5 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join t3 on c1 = c3;"""
qt_select_res28_6 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join [shuffle] t3 on c1 = c3;"""
qt_select_res28_7 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c1 = c3;"""
qt_select_res28_8 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3;"""
qt_select_res28_9 """select count(*) from t1 left semi join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c1 = c3;"""

// left join + left join + inner join
qt_select_res32_1 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res32_2 """select count(*) from t1 left join t2 on c1 = c2 left join [shuffle] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res32_3 """select count(*) from t1 left join t2 on c1 = c2 left join t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res32_4 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [shuffle] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res32_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res32_6 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res32_7 """select count(*) from t1 left join t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res32_8 """select count(*) from t1 left join t2 on c1 = c2 left join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res32_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res32_10 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res32_11 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res32_12 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res32_13 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""

// left join + right join + inner join
qt_select_res33_1 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res33_2 """select count(*) from t1 left join t2 on c1 = c2 right join [shuffle] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res33_3 """select count(*) from t1 left join t2 on c1 = c2 right join t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res33_4 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join [shuffle] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res33_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res33_6 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 right join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c3 = c4;"""
qt_select_res33_7 """select count(*) from t1 left join t2 on c1 = c2 right join [broadcast] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res33_8 """select count(*) from t1 left join t2 on c1 = c2 right join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res33_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 right join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res33_10 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3 join t4 on c3 = c4;"""
qt_select_res33_11 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res33_12 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""
qt_select_res33_13 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 right join t3 on c2 = c3 join [broadcast] t4 on c3 = c4;"""

// left join + semi join + inner join
qt_select_res34_1 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res34_2 """select count(*) from t1 left join t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res34_3 """select count(*) from t1 left join t2 on c1 = c2 left semi join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res34_4 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res34_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res34_6 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res34_7 """select count(*) from t1 left join t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res34_8 """select count(*) from t1 left join t2 on c1 = c2 left semi join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res34_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left semi join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res34_10 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res34_11 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res34_12 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res34_13 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""

// left join + anti join + inner join
qt_select_res35_1 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res35_2 """select count(*) from t1 left join t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res35_3 """select count(*) from t1 left join t2 on c1 = c2 left anti join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res35_4 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res35_5 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res35_6 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res35_7 """select count(*) from t1 left join t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res35_8 """select count(*) from t1 left join t2 on c1 = c2 left anti join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res35_9 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left anti join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res35_10 """select count(*) from t1 left join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res35_11 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res35_12 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res35_13 """select count(*) from t1 left join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""

// right join + semi join + inner join
qt_select_res36_1 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res36_2 """select count(*) from t1 right join t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res36_3 """select count(*) from t1 right join t2 on c1 = c2 left semi join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res36_4 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res36_5 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res36_6 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left semi join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res36_7 """select count(*) from t1 right join t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res36_8 """select count(*) from t1 right join t2 on c1 = c2 left semi join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res36_9 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left semi join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res36_10 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res36_11 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res36_12 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res36_13 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left semi join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""

// right join + anti join + inner join
qt_select_res37_1 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res37_2 """select count(*) from t1 right join t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res37_3 """select count(*) from t1 right join t2 on c1 = c2 left anti join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res37_4 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res37_5 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res37_6 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c2 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res37_7 """select count(*) from t1 right join t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res37_8 """select count(*) from t1 right join t2 on c1 = c2 left anti join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res37_9 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left anti join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res37_10 """select count(*) from t1 right join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join t4 on c1 = c4;"""
qt_select_res37_11 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res37_12 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res37_13 """select count(*) from t1 right join [shuffle] t2 on c1 = c2 left anti join t3 on c2 = c3 join [broadcast] t4 on c1 = c4;"""

// semi join + anti join + inner join
qt_select_res38_1 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join t3 on c1 = c3 join t4 on c1 = c4;"""
qt_select_res38_2 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join [shuffle] t3 on c1 = c3 join t4 on c1 = c4;"""
qt_select_res38_3 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join t3 on c1 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res38_4 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join [shuffle] t3 on c1 = c3 join t4 on c1 = c4;"""
qt_select_res38_5 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join t3 on c1 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res38_6 """select count(*) from t1 left semi join [broadcast] t2 on c1 = c2 left anti join [shuffle] t3 on c1 = c3 join [shuffle] t4 on c1 = c4;"""
qt_select_res38_7 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3 join t4 on c1 = c4;"""
qt_select_res38_8 """select count(*) from t1 left semi join t2 on c1 = c2 left anti join t3 on c1 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res38_9 """select count(*) from t1 left semi join [broadcast] t2 on c1 = c2 left anti join t3 on c1 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res38_10 """select count(*) from t1 left semi join [broadcast] t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3 join t4 on c1 = c4;"""
qt_select_res38_11 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res38_12 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join [broadcast] t3 on c1 = c3 join [broadcast] t4 on c1 = c4;"""
qt_select_res38_13 """select count(*) from t1 left semi join [shuffle] t2 on c1 = c2 left anti join t3 on c1 = c3 join [broadcast] t4 on c1 = c4;"""
